# Generated by Django 4.2.1 on 2023-05-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('genre_ids', models.JSONField()),
                ('length', models.IntegerField()),
                ('movie_id', models.IntegerField(unique=True)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
