# Generated by Django 4.2.1 on 2023-05-18 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('homepage', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField(unique=True)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255)),
                ('production_companies', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('runtime', models.IntegerField()),
                ('release_date', models.DateField()),
                ('tagline', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
