# Generated by Django 4.2.1 on 2023-06-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
