# Generated by Django 4.2.1 on 2023-06-01 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_production_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, null=True, size=None),
        ),
    ]
